# Generated by Django 5.0.6 on 2024-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='h', upload_to='images/', width_field='w'),
        ),
    ]
